use super::*;
use logex_types::QueryMemoryLimit;
use std::fs;
use tempfile::TempDir;

#[test]
fn sparse_subranges_reuse_a_checked_large_extent() {
    let tmp = TempDir::new().unwrap();
    let path = tmp.path().join("bundle");
    let expected: Vec<u8> = (0..2 * MAX_EXTENT_BYTES)
        .map(|i| ((i * 17) ^ (i / 31)) as u8)
        .collect();
    let writer = BundleWriter::create(&path).unwrap();
    writer.append_data(0, &expected).unwrap();
    let reference = writer.finish(1).unwrap();
    let memory = QueryMemoryBudget::new(QueryMemoryLimit::new(3 * MAX_EXTENT_BYTES).unwrap());
    let reader = BundleReader::open_with_memory(&path, &reference, Some(&memory)).unwrap();
    let clone = reader.clone();
    // Selected pages, reverse reads and repeated reads stay within the same
    // captured extent. Each must still equal independently generated bytes.
    for start in [3, 20_000, 70_000, 900_000, 3, 500_000] {
        assert_eq!(
            &*reader.read_range_accounted(0, start..start + 31).unwrap(),
            &expected[start as usize..start as usize + 31]
        );
    }
    assert_eq!(reader.file.lock().unwrap().reads.len(), 1);
    {
        let window = reader.file.lock().unwrap();
        assert_eq!(
            window.reads[0].end - window.reads[0].start,
            MAX_EXTENT_BYTES as u64
        );
    }
    assert_eq!(
        &*clone.read_range_accounted(0, 1_100_000..1_100_031).unwrap(),
        &expected[1_100_000..1_100_031]
    );
    assert_eq!(reader.file.lock().unwrap().reads.len(), 2);
    assert!(memory.used() < (MAX_EXTENT_BYTES + 1024) as u128);
    drop(reader);
    assert!(memory.used() >= MAX_EXTENT_BYTES as u128);
    drop(clone);
    assert_eq!(memory.used(), 0);
}

#[test]
fn cached_large_extent_does_not_hide_corruption_from_explicit_verification() {
    let tmp = TempDir::new().unwrap();
    let path = tmp.path().join("bundle");
    let writer = BundleWriter::create(&path).unwrap();
    writer.append_data(0, &vec![7; MAX_EXTENT_BYTES]).unwrap();
    let reference = writer.finish(1).unwrap();
    let reader = BundleReader::open(&path, &reference).unwrap();
    assert_eq!(reader.read_range(0, 0..29).unwrap(), vec![7; 29]);
    let mut bytes = fs::read(&path).unwrap();
    // Corruption is outside the selected subrange, but inside its extent.
    bytes[FILE_MAGIC.len() + 500_000] ^= 1;
    fs::write(&path, bytes).unwrap();
    assert!(reader.verify_all().is_err());
    assert!(
        BundleReader::open(&path, &reference)
            .unwrap()
            .read_range(0, 0..29)
            .is_err()
    );
}

#[test]
fn large_extent_allocation_failure_drops_the_previous_cache() {
    let tmp = TempDir::new().unwrap();
    let path = tmp.path().join("bundle");
    let writer = BundleWriter::create(&path).unwrap();
    writer.append_data(0, &[7; 100]).unwrap();
    writer.append_data(0, &vec![9; MAX_EXTENT_BYTES]).unwrap();
    let reference = writer.finish(1).unwrap();
    let memory = QueryMemoryBudget::new(QueryMemoryLimit::new(2 * MAX_EXTENT_BYTES).unwrap());
    let reader = BundleReader::open_with_memory(&path, &reference, Some(&memory)).unwrap();
    drop(reader.read_range_accounted(0, 0..1).unwrap());
    let cache = reader.file.lock().unwrap().bytes.capacity();
    assert!(cache > 0);
    let pressure = memory
        .reserve(
            memory.limit() - memory.used() as usize - 100,
            "test pressure",
        )
        .unwrap();
    let error = reader.read_range_accounted(0, 100..101).unwrap_err();
    assert!(
        error
            .get_ref()
            .unwrap()
            .is::<logex_types::QueryMemoryError>()
    );
    let window = reader.file.lock().unwrap();
    assert!(window.bytes.is_empty());
    assert_eq!(window.bytes.capacity(), 0);
    drop(window);
    drop(reader);
    drop(pressure);
    assert_eq!(memory.used(), 0);
}

#[test]
fn explicit_verification_uses_fresh_bounded_read_windows() {
    let tmp = TempDir::new().unwrap();
    let path = tmp.path().join("bundle");
    let writer = BundleWriter::create(&path).unwrap();
    let expected = vec![7; 2 * READ_AHEAD_BYTES + 31];
    for bytes in expected.chunks(97) {
        writer.append_data(0, bytes).unwrap();
    }
    let reference = writer.finish(1).unwrap();
    let reader = BundleReader::open(&path, &reference).unwrap();
    assert_eq!(reader.read_stream(0).unwrap(), expected);
    reader.file.lock().unwrap().reads.clear();
    reader.verify_all().unwrap();
    let window = reader.file.lock().unwrap();
    // A checksummed extent can cross a physical window boundary. Allow its
    // overlapping read, but never regress to one file read per tiny extent.
    assert!(window.reads.len() <= 2 * expected.len().div_ceil(READ_AHEAD_BYTES));
    let bytes_read = window.reads.iter().map(|r| r.end - r.start).sum::<u64>();
    assert!(bytes_read <= 2 * expected.len() as u64);
    assert!(
        bytes_read >= expected.len() as u64,
        "verification must reread all backing bytes despite a warm cache"
    );
    drop(window);
    let mut bytes = fs::read(&path).unwrap();
    bytes[FILE_MAGIC.len() + 50_000] ^= 1;
    fs::write(&path, bytes).unwrap();
    assert!(reader.verify_all().is_err());
}
