[package]
name = "logex-query"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
logex-types = { workspace = true }
logex-storage = { workspace = true }
logex-index = { workspace = true }
alloy-primitives = { workspace = true }
hex = "0.4"
roaring = "0.10"
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3"
