[package]
name = "logex-node"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "logex"
path = "src/main.rs"

[dependencies]
alloy-primitives = { workspace = true }
logex-cl = { workspace = true }
logex-types = { workspace = true }
logex-storage = { workspace = true }
logex-index = { workspace = true }
logex-server = { workspace = true }
logex-sync = { workspace = true }
reth-chainspec = { workspace = true }
reth-discv4 = { workspace = true }
reth-ethereum-forks = { workspace = true }
secp256k1 = { version = "0.30", features = ["global-context", "rand"] }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
libc = "0.2"

[target.'cfg(all(target_os = "linux", target_env = "gnu"))'.dependencies]
tikv-jemallocator = "0.6"

[dev-dependencies]
tempfile = "3"
